"""Render digest output: Markdown, standalone HTML, and JSON."""

from __future__ import annotations

import datetime
from datetime import timezone

CATEGORY_ORDER = ["paper", "changelog", "discussion"]
CATEGORY_LABEL = {
    "paper": "📄 Papers",
    "changelog": "📦 Tooling / Releases",
    "discussion": "💬 Discussions & News",
}


def summarize(text: str, topics: list[str]) -> str:
    """Local, dependency-free snippet. Swap for an LLM call when an API key is available."""
    sents = [s.strip() for s in text.replace("..", ".").split(".") if len(s.strip()) > 20]
    for s in sents:
        low = s.lower()
        if any(t in low for t in topics):
            return s[:150] + ("…" if len(s) > 150 else "")
    return (sents[0][:180] + "…") if sents else ""


def render_json(items: list[dict]) -> dict:
    return {
        "generated": datetime.datetime.now(timezone.utc).isoformat(),
        "count": len(items),
        "items": items,
    }


def _md_escape(t: str) -> str:
    return t.replace("|", "\\|")


def render_markdown(items: list[dict], generated: str) -> str:
    grouped: dict[str, list] = {}
    for it in items:
        grouped.setdefault(it["category"], []).append(it)

    lines = ["# Research Intelligence Digest", "",
             f"_Generated {generated} · {len(items)} items_", ""]
    for cat in CATEGORY_ORDER:
        rows = grouped.get(cat)
        if not rows:
            continue
        lines.append(f"## {CATEGORY_LABEL.get(cat, cat)}")
        lines.append("")
        for it in rows:
            url = _md_escape(it["url"])
            title = _md_escape(it["title"])
            tags = ", ".join(f"`{t}`" for t in it.get("tags", [])) if it.get("tags") else ""
            lines.append(f"- **[{title}]({url})** · {it['source_label']} · score {it['score']}")
            if tags:
                lines.append(f"  _tags:_ {tags}")
            if it.get("summary"):
                lines.append(f"  {_md_escape(it['summary'][:200])}")
            lines.append("")
    lines.append("---")
    lines.append("_Auto-generated by the research ingestion pipeline._")
    return "\n".join(lines)


def _esc(t: str) -> str:
    return (t.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def render_html(items: list[dict], generated: str) -> str:
    grouped: dict[str, list] = {}
    for it in items:
        grouped.setdefault(it["category"], []).append(it)

    body = ""
    for cat in CATEGORY_ORDER:
        rows = grouped.get(cat)
        if not rows:
            continue
        body += f"<h2>{CATEGORY_LABEL.get(cat, cat)}</h2><ul>"
        for it in rows:
            tags = " ".join(f'<span class="tag">{t}</span>' for t in it.get("tags", []))
            body += (f'<li><b><a href="{_esc(it["url"])}">{_esc(it["title"])}</a></b>'
                     f'<br/><span class="meta">{_esc(it["source_label"])} · score {it["score"]} {tags}</span>')
            if it.get("summary"):
                body += f'<div class="sum">{_esc(it["summary"][:220])}</div>'
            body += "</li>"
        body += "</ul>"

    return ("<!doctype html><html><head><meta charset='utf-8'>"
            "<meta name='viewport' content='width=device-width,initial-scale=1'>"
            "<title>Research Digest</title>"
            "<style>body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:900px;"
            "margin:28px auto;padding:0 20px;color:#222;line-height:1.5}"
            "h1{color:#0a3d62}h2{border-bottom:2px solid #eef;padding-bottom:4px;margin-top:30px}"
            "ul{list-style:none;padding:0}.tag{font-size:11px;background:#eef4ff;border:1px solid #ccd;"
            "border-radius:10px;padding:1px 7px;margin-left:4px}.meta{color:#888;font-size:13px}"
            ".sum{color:#555;font-size:13px;margin:4px 0 12px}a{color:#0a6cff;text-decoration:none}"
            "a:hover{text-decoration:underline}</style></head><body>"
            f"<h1>Research Intelligence Digest</h1>"
            f"<p><em>Generated {generated} · {len(items)} items</em></p>"
            f"{body}"
            "<hr><p><small>Auto-generated by the research ingestion pipeline.</small></p>"
            "</body></html>")