#!/usr/bin/env python3
"""analyze_concept_graph.py — basic graph analysis of the concept graph.

Minimal, portable, deterministic. Reads concept_graph.json (from
relate_concepts.py) and computes basic network metrics: degree / weighted
degree, degree centrality, PageRank, betweenness (nodes + edges), clustering
coefficient, connected components, and label-propagation communities.
Writes concept_graph_analysis.json and (optionally) a human-readable
concept_graph_analysis.md.

    python3 tools/relate_concepts.py --concepts concepts.json --write-doc \
        > concept_graph.json
    python3 tools/analyze_concept_graph.py --graph concept_graph.json --write-doc

Only stdlib. Composes with extract/relate; works on any repo that has a
concept_graph.json (i.e. any *-research repo after the concept pipeline).
"""
import argparse
import json
import math
import sys
from collections import defaultdict, deque
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FOOTER = "Generated by `tools/analyze_concept_graph.py` — do not edit by hand."


def load_graph(path):
    with open(path, encoding="utf-8") as f:
        g = json.load(f)
    nodes = {n["id"]: n for n in g["nodes"]}
    adj = defaultdict(dict)  # id -> {neighbor: weight}
    for e in g["edges"]:
        a, b, w = e["source"], e["target"], e.get("weight", 1)
        adj[a][b] = adj[a].get(b, 0) + w
        adj[b][a] = adj[b].get(a, 0) + w
    return nodes, adj


def pagerank(adj, d=0.85, iters=60):
    nodes = list(adj)
    n = len(nodes)
    if n == 0:
        return {}
    pr = {v: 1.0 / n for v in nodes}
    for _ in range(iters):
        nxt = {v: (1 - d) / n for v in nodes}
        for v in nodes:
            wdeg = sum(adj[v].values())
            if wdeg == 0:
                continue
            for w, wgt in adj[v].items():
                nxt[w] += d * pr[v] * (wgt / wdeg)
        pr = nxt
    return pr


def node_betweenness(adj):
    nodes = list(adj)
    C = {v: 0.0 for v in nodes}
    for s in nodes:
        pred = {v: [] for v in nodes}
        sigma = {v: 0 for v in nodes}; sigma[s] = 1
        dist = {v: -1 for v in nodes}; dist[s] = 0
        queue = deque([s])
        order = []
        while queue:
            v = queue.popleft()
            order.append(v)
            for w in adj[v]:
                if dist[w] < 0:
                    dist[w] = dist[v] + 1
                    queue.append(w)
                if dist[w] == dist[v] + 1:
                    sigma[w] += sigma[v]
                    pred[w].append(v)
        delta = {v: 0.0 for v in nodes}
        for w in reversed(order):
            for v in pred[w]:
                delta[v] += (sigma[v] / sigma[w]) * (1 + delta[w])
            if w != s:
                C[w] += delta[w]
    for v in C:
        C[v] /= 2.0
    return C


def edge_betweenness(adj):
    nodes = list(adj)
    E = defaultdict(float)
    for s in nodes:
        pred = {v: [] for v in nodes}
        sigma = {v: 0 for v in nodes}; sigma[s] = 1
        dist = {v: -1 for v in nodes}; dist[s] = 0
        queue = deque([s])
        order = []
        while queue:
            v = queue.popleft()
            order.append(v)
            for w in adj[v]:
                if dist[w] < 0:
                    dist[w] = dist[v] + 1
                    queue.append(w)
                if dist[w] == dist[v] + 1:
                    sigma[w] += sigma[v]
                    pred[w].append(v)
        delta = {v: 0.0 for v in nodes}
        for w in reversed(order):
            for v in pred[w]:
                c = (sigma[v] / sigma[w]) * (1 + delta[w])
                delta[v] += c
                E[tuple(sorted((v, w)))] += c / 2.0
    return E


def clustering(adj):
    out = {}
    for v in adj:
        neigh = list(adj[v])
        k = len(neigh)
        if k < 2:
            out[v] = 0.0
            continue
        links = 0
        nset = set(neigh)
        for a in neigh:
            for b in adj[a]:
                if b in nset and b != a:
                    links += 1
        out[v] = links / (k * (k - 1))
    return out


def components(adj):
    seen = set()
    comps = []
    for v in adj:
        if v in seen:
            continue
        q = deque([v]); seen.add(v); comp = []
        while q:
            x = q.popleft(); comp.append(x)
            for w in adj[x]:
                if w not in seen:
                    seen.add(w); q.append(w)
        comps.append(comp)
    return sorted(comps, key=lambda c: -len(c))


def communities(adj, iters=25):
    nodes = sorted(adj)
    label = {v: v for v in nodes}
    for _ in range(iters):
        changed = False
        for v in nodes:
            counts = {}
            for w, wgt in adj[v].items():
                counts[label[w]] = counts.get(label[w], 0) + wgt
            if counts:
                mx = max(counts.values())
                best = min(l for l, c in counts.items() if c == mx)
                if best != label[v]:
                    label[v] = best
                    changed = True
        if not changed:
            break
    groups = defaultdict(list)
    for v in nodes:
        groups[label[v]].append(v)
    return list(groups.values())


def modularity(adj, comms):
    nodes = list(adj)
    m = sum(len(adj[v]) for v in nodes) / 2.0
    if m == 0:
        return 0.0
    deg = {v: sum(adj[v].values()) for v in nodes}
    comm_of = {}
    for i, c in enumerate(comms):
        for v in c:
            comm_of[v] = i
    q = 0.0
    for v in nodes:
        for w, wgt in adj[v].items():
            if comm_of.get(v) == comm_of.get(w):
                q += wgt - (deg[v] * deg[w]) / (2 * m)
    return q / (2 * m)


def main():
    ap = argparse.ArgumentParser(description="Basic graph analysis of concept_graph.json.")
    ap.add_argument("--graph", default="concept_graph.json")
    ap.add_argument("--write-doc", action="store_true",
                    help="write docs/research/concept_graph_analysis.md")
    args = ap.parse_args()

    nodes, adj = load_graph(args.graph)
    n = len(nodes)

    pr = pagerank(adj)
    nb = node_betweenness(adj)
    eb = edge_betweenness(adj)
    cl = clustering(adj)
    comps = components(adj)
    comms = communities(adj)
    q = modularity(adj, comms)

    node_rows = []
    for vid, node in nodes.items():
        deg = len(adj[vid])
        wdeg = sum(adj[vid].values())
        node_rows.append({
            "id": vid, "term": node["term"], "kind": node.get("kind"),
            "df": node.get("df", 0),
            "degree": deg, "weighted_degree": wdeg,
            "degree_centrality": round(deg / (n - 1), 4) if n > 1 else 0.0,
            "pagerank": round(pr.get(vid, 0.0), 6),
            "betweenness": round(nb.get(vid, 0.0), 4),
            "clustering": round(cl.get(vid, 0.0), 4),
        })
    node_rows.sort(key=lambda r: -r["pagerank"])

    term = {vid: nodes[vid]["term"] for vid in nodes}
    top_hubs = [r["term"] for r in node_rows[:10]]
    bridge_nodes = [r["term"] for r in sorted(node_rows, key=lambda r: -r["betweenness"])[:10]
                    if r["betweenness"] > 0]
    bridge_edges = []
    for (a, b), w in sorted(eb.items(), key=lambda kv: -kv[1])[:15]:
        if w > 0:
            bridge_edges.append({"source": term[a], "target": term[b],
                                 "weight": adj[a][b], "edge_betweenness": round(w, 4)})

    comm_list = []
    for c in sorted(comms, key=lambda c: -len(c)):
        comm_list.append({"size": len(c),
                          "members": sorted(term[v] for v in c)})

    result = {
        "stats": {"nodes": n, "edges": sum(len(adj[v]) for v in adj) // 2,
                  "components": len(comps), "communities": len(comms),
                  "modularity": round(q, 4)},
        "nodes": node_rows,
        "communities": comm_list,
        "top_hubs": top_hubs,
        "bridge_nodes": bridge_nodes,
        "bridge_edges": bridge_edges,
    }
    print(json.dumps(result, indent=2, ensure_ascii=False))

    if args.write_doc:
        out = REPO / "docs" / "research" / "concept_graph_analysis.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        L = ["# Concept Graph Analysis", "",
             f"**Generated:** {n} nodes, {result['stats']['edges']} edges, "
             f"{len(comps)} components, {len(comms)} communities "
             f"(modularity {round(q,3)}). Edges = co-occurrence.", ""]
        L += ["## Top hubs (by PageRank)", ""]
        for r in node_rows[:12]:
            L.append(f"- **{r['term']}** — PR {r['pagerank']:.4f}, "
                     f"degree {r['degree']}, df {r['df']}")
        L += ["", "## Bridge nodes (high betweenness — connect clusters)", ""]
        if bridge_nodes:
            for t in bridge_nodes[:10]:
                L.append(f"- {t}")
        else:
            L.append("- (none)")
        L += ["", "## Bridge edges (high edge-betweenness)", ""]
        if bridge_edges:
            for e in bridge_edges[:10]:
                L.append(f"- {e['source']} ↔ {e['target']} "
                         f"(weight {e['weight']}, EB {e['edge_betweenness']})")
        else:
            L.append("- (none)")
        L += ["", "## Communities (clusters of related concepts)", ""]
        for i, c in enumerate(comm_list[:12]):
            members = ", ".join(c["members"][:12])
            L.append(f"### Cluster {i+1} ({c['size']} concepts)")
            L.append("")
            L.append(members)
            L.append("")
        L.append("")
        L.append(FOOTER)
        out.write_text("\n".join(L), encoding="utf-8")
        print(f"Wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
