#!/usr/bin/env python3
"""relate_concepts.py — relate extracted concepts into a knowledge graph.

Minimal, portable, deterministic. Reads papers.yaml + concepts.json (from
extract_concepts.py) and builds a relationship graph where edges are
*co-occurrence*: two concepts that appear in the same paper relate, weighted
by the number of shared papers. Writes concept_graph.json and (optionally)
a human-readable concept_map.md.

    python3 tools/extract_concepts.py --papers papers.yaml > concepts.json
    python3 tools/relate_concepts.py --papers papers.yaml \
        --concepts concepts.json --write-doc

Concept paper-sets are rebuilt here from the `match` descriptor each concept
carries: taxonomy categories are matched STRUCTURALLY (paper.category field);
curated/emergent terms by TEXT. Only stdlib + PyYAML. Composes with
extract_concepts.py; works on any repo with papers.yaml.
"""
import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
TOKEN = re.compile(r"[a-z][a-z\-]+")
FOOTER = "Generated by `tools/relate_concepts.py` — do not edit by hand."


def load_papers(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f).get("papers", [])


def load_concepts(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data.get("concepts", data) if isinstance(data, dict) else data


def paper_set(ei, papers, match):
    """Return set of paper indices for one concept, using its match descriptor."""
    if match["type"] == "field":
        fld, val = match["field"], match["value"]
        return {i for i, e in enumerate(papers) if e.get(fld) == val}
    # text
    pats = [re.compile(rf"\b{re.escape(frm)}\b") for frm in match["forms"]]
    toks = [set(frm.split()) for frm in match["forms"]]
    out = set()
    for i, e in enumerate(papers):
        text = f" {e.get('title','')} {e.get('abstract','')} ".lower()
        tset = set(TOKEN.findall(text))
        if any(tk <= tset and p.search(text) for tk, p in zip(toks, pats)):
            out.add(i)
    return out


def main():
    ap = argparse.ArgumentParser(description="Relate concepts into a graph.")
    ap.add_argument("--papers", default="papers.yaml")
    ap.add_argument("--concepts", default="concepts.json")
    ap.add_argument("--top", type=int, default=80,
                    help="max concepts (by df) to relate; seeds always included")
    ap.add_argument("--min-co", type=int, default=2,
                    help="min shared papers for an edge")
    ap.add_argument("--write-doc", action="store_true",
                    help="write docs/research/concept_map.md")
    args = ap.parse_args()

    papers = load_papers(args.papers)
    concepts = load_concepts(args.concepts)

    seeds = [c for c in concepts if c.get("seed")]
    others = sorted((c for c in concepts if not c.get("seed")),
                    key=lambda x: -x.get("df", 0))
    active = (seeds + others)[:args.top]
    seen = {c["term"] for c in active}
    active = active + [c for c in seeds if c["term"] not in seen]
    active = active[:args.top + len(seeds)]

    # build paper-sets
    psets = [paper_set(i, papers, c["match"]) for i, c in enumerate(active)]

    # invert: paper -> active concept indices
    pmap = defaultdict(list)
    for ci, s in enumerate(psets):
        for pi in s:
            pmap[pi].append(ci)

    co = Counter()
    for lst in pmap.values():
        for a, b in combinations(lst, 2):
            co[(a, b)] += 1

    nodes = [{"id": i, "term": c["term"], "kind": c["kind"], "df": c.get("df", 0)}
             for i, c in enumerate(active)]
    edges = [{"source": a, "target": b, "weight": w}
             for (a, b), w in co.items() if w >= args.min_co]

    adj = defaultdict(list)
    for e in edges:
        adj[e["source"]].append((e["target"], e["weight"]))
        adj[e["target"]].append((e["source"], e["weight"]))

    graph = {"nodes": nodes, "edges": edges,
             "stats": {"concepts": len(nodes), "edges": len(edges),
                       "papers": len(papers)}}
    print(json.dumps(graph, indent=2, ensure_ascii=False))

    if args.write_doc:
        out = REPO / "docs" / "research" / "concept_map.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        lines = ["# Concept Map — Knowledge Graph of the Corpus",
                 "",
                 f"**Generated:** {len(nodes)} concepts, {len(edges)} relationships "
                 f"from {len(papers)} papers. Edges = co-occurrence (shared papers).",
                 "",
                 "## Top concepts",
                 "",
                 "| Concept | Kind | Papers |",
                 "|----------|------|--------|"]
        for c in active[:40]:
            lines.append(f"| {c['term']} | {c['kind']} | {c.get('df',0)} |")
        lines.append("")
        lines.append("## Relationships (top concepts → related concepts)")
        lines.append("")
        for c in active[:25]:
            i = active.index(c)
            rels = sorted(adj[i], key=lambda x: -x[1])[:8]
            if not rels:
                continue
            lines.append(f"### {c['term']}")
            lines.append("")
            for j, w in rels:
                lines.append(f"- {active[j]['term']} — {w} shared paper(s)")
            lines.append("")
        lines.append("")
        lines.append(FOOTER)
        out.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
